name: issue created

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  thing:
    name: issue conversation
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./.github/workflows

    steps:
      - uses: docker://mgwalker/fat-bear-bracketeer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}